### ISSUE TITLE
Home of the source

### ISSUE THREAD

**Issue by jonaskello** [IdentityModel/TokenManager#2]
Just wanted to check if this is till the home repo of the source for the oidc token manager. I noticed the samples were updated to a new library version but I cannot find the home repo for this.

https://github.com/IdentityServer/IdentityServer3.Samples/commit/fc48fcd43edefc3c5d1414569f83ec0d9d374c61

There are two more repos but they are empty as far as I can see:

https://github.com/IdentityModel/OidcTokenManager
https://github.com/IdentityModel/OidcClient

Specifically I am porting the code to Google Dart but I don't know which repo to watch to look for new changes....

**Comment by brockallen** [comment]
I'm in the middle of setting up the new Oidc* ones -- by this weekend they'll be the ones to use.

**Comment by jonaskello** [comment]
Thanks, I'll watch the new ones and check my port against them ones they are set up. I might be able to help with the docs if they are not done yet. But first I need to understand how to use the library myself, I'm working on that part right now :-).

**Comment by brockallen** [comment]
If you're in the Boston area this weekend: https://twitter.com/BostonCodeCamp/status/577960021457289216

**Comment by jonaskello** [comment]
Looks perfect, but I'm based in Sweden so it is a bit too far :-). But if there is any videos or slides/notes shared after that session I would very much like to view them.
